build:
  id: 101
  version: 1.2.3
  name: "Default-Build-changes"
  type: "Default Build changes"

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  management:
    endpoint:
      web:
        exposure:
          include: *
